
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://lxynox.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: "UA-85743116-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "lxynox"
title: "△ lxynox ▼"
description: "A panda rambles on the web, speaks a little bit JavaScript for fun #👶dev_for_life"
keywords: "jekyll, blog, personal site"
favicon: "/img/profile.ico"

################
# Header layout #
################

black-favicon: "/img/profile.ico"

background-img: "../img/bg_vimrc.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add  HTML Tags in the Text
  - text: "One of the greatest pleasures in life is doing what other people say you cannot. - Sindre Sorhus"
  - text: "Those who are crazy enough to think they can change the world usually do. - Steve Jobs"
  - text: "The dream of yesterday, is the hope of today, and the reality of tomorrow. - Robert H. Goddard"

me-img: "/img/profile.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

############
# Timeline #
############

events:
  - image: "/img/timeline/react_logo.png"
    date: "June, 2016 - Today"
    description: ""
  - image: "/img/timeline/CA_logo.jpg"
    date: "Jan, 2016 - May, 2016"
    description: ""
  - image: "/img/timeline/WPI_logo.png"
    date: "Sep 2014 - May, 2016"
    description: ""
  - image: "/img/timeline/BIT_logo.png"
    date: "Sep 2010 - May, 2014" 
    description: ""

# First image of the Timeline

timeline-img: "/img/timeline/default.gif"

###########
# Contact #
###########

email: "lxynox@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/lxynox"
  - title: "twitter"
    url: "https://twitter.com/lxynox"
  - title: "github"
    url: "https://github.com/lxynox"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
